### ISSUE TITLE
Not installing typings for node itself

### ISSUE THREAD

**Issue by ghost** [jvitor83/typings-autoinstaller#10]
On initial installing typings for all dependencies, no typing for node is created. (For node itself: http, path etc.)

**Comment by ghost** [comment]
(I use your extension with Javascript projects, not Typescript)

**Comment by jvitor83** [comment]
@VitalySenko what you mean "I use your extension with Javascript projects"?

The typings tool is for use with a typescript project, since it executes the comand:

``` shell
typings install dt~jquery --global --save
```

to grab every definition (d.ts) from yours npm package installed.

_Basically it tries to keep typings.json in sync with your package.json_

Can you show more details about your problem?

**Comment by ghost** [comment]
VS Code provides IntelliSense in **Javascript** for those npm modules which have typings in your project.
For example, i install "passport" with save in package.json. Your extension automatically install typings for it. And i have full autocomplete for `var passport= require('passport');` in my javascript-only project!
![exm](https://cloud.githubusercontent.com/assets/12730311/16870397/f4fd84ae-4a89-11e6-8f5f-f20a9a446a2d.png)

But to activate autocompletion for node core modules (or __dirname for example), i need to manually install typings for node. (your extension looks only through dependencies).
![exm2](https://cloud.githubusercontent.com/assets/12730311/16870455/4a5c1e06-4a8a-11e6-8f17-86b40865ede6.png)

**Comment by jvitor83** [comment]
I don't know for sure if my extension should automatically install extensions for nodejs since this is specific to a environment.
There is some way to detect if the package.json is for a NodeJs platform to see if i can add those typings?

**Comment by ghost** [comment]
Maybe it should check for jsconfig.json file...
This is file for JS projects which enable autocomplete (as i remember).

**Comment by Shadowfaxenator** [comment]
package.json has a special property:

``` javascript
{
"engines":
"node":">6.0.0"
}
```

could you use it?

**Comment by jvitor83** [comment]
Ok, my idea is when you run the command F1 -> `Typings: Install definitions for all dependencies`, it will install typings based on the engine too.

This way, if your package.json has the engine node like @Shadowfaxenator said, once you run manually the command to install all dependencies it will run the command to install the typings of the engine.

In the package.json sample:

```
"engines": {
      "node": ">6.0.0"
  }
```

Will result in: `typings install dt~node --global --save`

I'm guessing this behavior should do the work.

The branch https://github.com/jvitor83/typings-autoinstaller/tree/develop has a preview of this. Will release soon.

**Comment by jvitor83** [comment]
Got a better idea.
Now i consider the "engines" property as a source to watch for installing and uninstalling typings too.
Get even better this way.
