### ISSUE TITLE
Issues when multiple typings (un)install commands are running in parallel

### ISSUE THREAD

**Issue by skolmer** [jvitor83/typings-autoinstaller#6]
The current version of the extension is running all typings commands in parallel. This oftentimes leads to concurrent file access on typings.json and index.ts.d and not all typings are installed. This can be reproduced if you add multiple new dependencies to your package.json. I have created a pull request #5  that changes this behavior by running one command after another. The changes also result in a better readable console output.

**Comment by jvitor83** [comment]
Resolved in PR
