### ISSUE TITLE
There is a new way install d.ts in TypeScript 2

### ISSUE THREAD

**Issue by frogcjn** [jvitor83/typings-autoinstaller#8]
Please see:
https://github.com/Microsoft/TypeScript/issues/9184

maybe you can consider to support it with your plugin.

**Comment by jvitor83** [comment]
Once the Typescript 2.0 was released, i will try to update this VSCode plugin to manage those npm types.
This will be another breaking change. But i will make this explicit in the readme.

**Comment by jvitor83** [comment]
I have created a new plugin to support Typescript 2+.
[https://marketplace.visualstudio.com/items?itemName=jvitor83.types-autoinstaller](https://marketplace.visualstudio.com/items?itemName=jvitor83.types-autoinstaller)
Fell free to try it out.
I will keep this as a depreciated version and put a link to the new one once version 2 of typescript get released (out of beta).

**Comment by frogcjn** [comment]
Thanks!

**Comment by tamj0rd2** [comment]
Awesome! This is better to use than the original extension because you don't have to add the /// reference lines to files :)
