### ISSUE TITLE
Issue with bower

### ISSUE THREAD

**Issue by rbatukaev** [jvitor83/typings-autoinstaller#9]
Installing typings from bower.json throws the following errors:

![image](https://cloud.githubusercontent.com/assets/4622415/16647946/5b65cbe4-443a-11e6-8dc6-d0fe00b353b6.png)

**Comment by jvitor83** [comment]
@rbatukaev, i could not reproduce your problem.
Can you put your `bower.json` or show a repo with this issue?

**Comment by jvitor83** [comment]
Without the `bower.json` i cannot reproduce your problem.
